### ISSUE TITLE
support or option reading the multiple changelog file under single repository 

### ISSUE THREAD

**Issue by vijaykumarv7** [sanjP10/release#49]
I'm already using the releases to check the changelog file and move on to further stage in my Jenkins.

I have use-case which needs to reads multiple changelog file in each folder of the repository to validate the changes. 

Would it be possible to make with this release function.

**Comment by sanjP10** [comment]
@vijaykumarv7 could you provide me an example repo and give me more details on why you have multiple changelog files please?

Is it a repository or is it a repository with submodules?
